name: flutter_full_pdf_viewer_null_safe
description: A flutter plugin to display PDF. This works for Android and for iOS.
version: 1.0.0
homepage: https://github.com/rohitsangwan01/flutter_full_pdf_viewer_null_safe

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
